### PR TITLE
Feature puzzle casey

### PR DESCRIPTION
**Pull request by caclowers**
Revised puzzle description and renamed branch for consistency.

### CODE REVIEW

**Comment by LukeSchlangen** [comment]
This is fun! I like that it's different from the others. My comments:

- I think I would stick to calling it "Walk in a circle" or "Walk in a triangle" for consistency.
- I think I would have it rotate another 60 degrees at the end (to avoid people getting angry about the technicality about how the can't is rotated, and could therefor be considered in a different position)
- I'm not actually sure what the best way to present the answer is here. The `Broadcast` block does something kind of specific and weird in scratch, but because this puzzle is different, it's not like we can have it print the answer... maybe it can check its x/y position? Is there a way we could actually have it check its position and say the answer like the other puzzles? I think if we do that, we should definitely bump up the difficulty level. (Level 4? Level 5? ...I honestly didn't think through what the different levels meant.)

A lot of comments because you pushed the envelope with this one, not because I don't like it. I think it's neat!

**Comment by caclowers** [comment]
ok thanks Luke!

**Comment by caclowers** [comment]
> 
> For something like this, we might even want to go a step further and include an image in the answer? 
> 

I'm trying my darndest to include a gif of the puzzle actually running and can not figure out how to include it. The templates/puzzle.js stipulate that the answer is "answer: PropTypes.string.isRequired"

so i just get a string when I include a link to giphy - 
answer: "FALSE, you are halfway around a hexagon. It would take three more moves to return to the starting spot [Answer](https://gph.is/2ROHIFO)"

I also tried adding the image into the answer instead of an outside link - 
answer: "FALSE, you are halfway around a hexagon. It would take three more moves to return to the starting spot 
alt text"

any ideas?

**Comment by LukeSchlangen** [comment]
Ooooh... yeah... so the way I'm using the markdown is essentially just like an object with a string. To use an actual markdown section, you would write it below the `-----------` line in the file, and you would also have to create a section for actual markdown in the file template. You'll also need to Dangerously set HTML for this to work:

https://www.gatsbyjs.org/tutorial/part-seven/#creating-pages

It's not easy, but could be a fun challenge if you're up for it!

If that works, I would love for the gif to be stored in the project (instead of a 3rd party site), but that might be an issue for the GitHub Repo size limit?

**Comment by caclowers** [comment]
I’m up for it! I’ll look into storing it in the project and size limits

**Comment by LukeSchlangen** [comment]
Hi @caclowers ! I just noticed, would you be able to close this PR and reopen a PR into Develop. Our process will go `Feature` -> `Develop` -> `Master`

Thank you!

**Comment by caclowers** [comment]
absolutely, my bad

**Pull request closed without merging**
